version: '2'
services:

  db:
    image: postgres:9.4-alpine
    volumes:
      - "./docker/db/pgdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: associados
      POSTGRES_HOST_AUTH_METHOD: trust

  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ".:/usr/src/app"
    environment:
      DATABASE_URL: postgresql://postgres@db/associados
      DEBUG: 1
      LOCAL_STATIC: 1
      SECRET_KEY: super-secreto
