version: '2'
services:

  db:
    image: postgres:9.4
    ports:
      - "5432:5432"
    volumes:
      - "./docker/db/pgdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: assocdev
      POSTGRES_USER: associados
      POSTGRES_DB: associados

  web:
    build: .
    command: bash -c "python check_db.py --service-name Postgres --ip db --port 5432 &&
                      python manage.py migrate --settings associados.settings && 
                      python manage.py loaddata --settings associados.settings app/core/fixtures/site_init.json &&
                      python manage.py runserver 0.0.0.0:8000 --settings associados.settings_local"
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ".:/usr/src/app"
