version: '3.9'

services:

  db:
    image: postgres:12-alpine
    volumes:
      - "./docker/db/pgdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: associados
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: pg_isready -Upostgres
      interval: 1s
      timeout: 30s

  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      db: {condition: service_healthy}
    volumes:
      - ".:/usr/src/app"
    environment:
      DATABASE_URL: postgresql://postgres@db/associados
      DEBUG: 1
      LOCAL_STATIC: 1
      SECRET_KEY: super-secreto
