#!/usr/bin/env python
# coding: utf-8
"""
Django settings for python-brasil associados project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""
import os

from split_settings.tools import include


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


if os.environ['DJANGO_SETTINGS_MODULE'] == 'associados.settings.localhost':
    # must bypass this block if another settings module was specified
    include("base.py", scope=locals())

# This is a security measure to prevent HTTP Host header attacks.
# https://docs.djangoproject.com/pt-br/1.11/ref/settings/#allowed-hosts

ALLOWED_HOSTS = ['*']


# This is a security measure to prevent HTTP Host header attacks.
# https://docs.djangoproject.com/pt-br/1.11/ref/settings/#internal-ips

INTERNAL_IPS = ['127.0.0.1']


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

ADMIN_MEDIA_PREFIX = STATIC_URL + 'admin/'
