#!/usr/bin/env python
# coding: utf-8
"""
Django settings for associados project.

Generated by 'django-admin startproject' using Django 1.10.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""
import os

from split_settings.tools import include
from decouple import config


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


if os.environ['DJANGO_SETTINGS_MODULE'] == 'associados.settings.production':
    # must bypass this block if another settings module was specified
    include("base.py", scope=locals())


# SSL Setup

SECURE_SSL_REDIRECT = config('FORCE_HTTPS', cast=bool, default=False)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# AWS Settings

STATIC_S3_PATH = "static"
DEFAULT_S3_PATH = "media"


AWS_ACCESS_KEY_ID = config('BUCKET_ACCESS_KEY', default='')
AWS_SECRET_ACCESS_KEY = config('BUCKET_SECRET_KEY', default='')
AWS_STORAGE_BUCKET_NAME = config('BUCKET_NAME', default='')
AWS_REGION_BUCKET_NAME = config("BUCKET_REGION", default='')


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

DEFAULT_FILE_STORAGE = config('DEFAULT_FILE_STORAGE', default='s3_folder_storage.s3.DefaultStorage')

STATICFILES_STORAGE = config('STATICFILES_STORAGE', default='s3_folder_storage.s3.StaticStorage')

MEDIA_ROOT = config('MEDIA_ROOT', default='/%s/' % DEFAULT_S3_PATH)

MEDIA_URL = config('MEDIA_URL', default='//%s.%s.amazonaws.com/media/' % (
    AWS_STORAGE_BUCKET_NAME,
    AWS_REGION_BUCKET_NAME
))

STATIC_ROOT = config('STATIC_ROOT', default="/%s/" % STATIC_S3_PATH)

STATIC_URL = config('STATIC_URL', default='//%s.%s.amazonaws.com/static/' % (
    AWS_STORAGE_BUCKET_NAME,
    AWS_REGION_BUCKET_NAME
))

ADMIN_MEDIA_PREFIX = STATIC_URL + 'admin/'
