# Generated by Django 2.2.24 on 2021-12-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20151129_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='diretoria',
            field=models.NullBooleanField(default=False, verbose_name='Diretoria'),
        ),
        migrations.AlterField(
            model_name='member',
            name='thumb_image',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Thumbimage'),
        ),
    ]
