# Generated by Django 2.2.24 on 2021-12-02 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_pending_migrations_after_django_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ('user__first_name', 'user__last_name'), 'verbose_name_plural': 'Members'},
        ),
    ]
