# Generated by Django 2.2.24 on 2021-12-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20150830_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttype',
            name='duration',
            field=models.IntegerField(default=1, help_text='In days'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('1', 'Awaiting Payment'), ('2', 'In analysis'), ('3', 'Paid'), ('4', 'Available'), ('5', 'In dispute'), ('6', 'Returned'), ('7', 'Cancelled')], max_length=1),
        ),
    ]
