name: Run tests

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build image for web service
      run: docker compose build web

    - name: Build image for db service
      run: docker compose pull db

    - name: Run tests
      run: ./bin/run pytest
