name: Run tests

on:
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build image
      run: docker-compose build

    - name: Run tests
      run: docker compose run --rm web python manage.py test
